language: ruby
rvm:
- 2.1
# 假如 bundler 被使用，安装时将运行 `bundle install`.
script: ./bin/cibuild

# 分支白名单
branches:
  only:
  - gh-pages     # 测试 gh-pages 分支

env:
  global:
  - NOKOGIRI_USE_SYSTEM_LIBRARIES=true # 为 html-proofer 的安装加速