# Site settings
title: Android工程师
email: jinmiao0601@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  作者注：作为一名移动互联网技术从业者，拥有一个自己的Blog，是一件很骄傲的事情。</br></br>
  分享是一种美德，学习是一种信仰。
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://androideng.com" # the base hostname & protocol for your site
github_username: jinmiao

# Build settings
markdown: kramdown
