# Site settings
title: 欧阳金苗の博客
email: oyjm0601@yeah.net
description: > # this means to ignore newlines until "baseurl:"
  码农自留地</br></br>
  学习是一种信仰，分享是一种美德。
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://ouyangjinmiao.com" # the base hostname & protocol for your site
github_username: jinmiao

# Build settings
markdown: kramdown


# 添加多说评论组件
# comments :
   # provider : duoshuo
  #  duoshuo :
 #     short_name : jinmiao

# theme: jekyll-theme-hacker
